name: solar-system Workflow

on:
   workflow_dispatch:
   push:
     branches:
       - main
       - 'feature/*'
    
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  
  testing: 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18, 19, 20]
        exclude:
          - os: macos-latest
            node-version: 18
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup node-version
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: installing npm
        run: npm install

      - name: test
        run: npm test

      - name: upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
            name: test-result of ${{ github.job }}-${{matrix.os}}-${{matrix.node-version}}
            path: test-results.xml
            if-no-files-found: ignore